ORG 1000H
CADENA DB "FGR"
       DB 00H
ORG 3000H
CONTAR_MIN: MOV DX,0 ; CONTADOR DE MINUSCULAS
SALTO: MOV CL,[BX] ; PASO CARACTER A CL
CMP CL,0 ; REVISO SI ES EL FIN DE LA CADENA
JZ FIN ; SI ES EL FIN, TERMINA LA SUBRUTINA
INC BX ;SINO, BX VA A TENER EL PROXIMO CARCTER
CMP CL,61H ; COMPARO CL CON a
JS SALTO ; SI ES NEGATIVO, CL TIENE UN VALOR MENOR A a POR LO QUE NO ES MINUSCULA: VUELVO A SALTO
CMP CL,7AH ;SINO, COMPARO CON z
JNS SALTO ; SI DA NEGATIVO SIGNIFICA QUE NO ES MINUSCULA: VUELVO A SALTO
INC DX ; INCREMENTO EL CONTADOR DE MINUSCULAS
JMP SALTO 
FIN: RET
ORG 2000H
MOV BX,OFFSET CADENA
CALL CONTAR_MIN
HLT
END