ORG 1000H
CAD DB "abcDb!"
 DB 0
CAR DB "b"
ORG 3000H
CONTAR_CAR: MOV BX,SP ;FA
ADD BX,2
MOV CX,[BX];CX TIENE EL CARACTER
ADD BX,2
MOV BX,[BX];BX TIENE LA DIRECCION DE LA CADENA
COMPA: CMP CH,[BX] ;COMPARO EL CARACTER DE LA CADENA CON EL CARACTER 
JZ SUMAR
INC BX
CMP AH,[BX]
JZ FINALIZAR
JMP COMPA
SUMAR:INC DX
INC BX
JMP COMPA
FINALIZAR: RET
ORG 2000H
MOV BX,OFFSET CAD
PUSH BX ;FE TIENE LA CADENA
MOV BH,CAR
PUSH BX ;FC TIENE EL CARACTER
MOV DX,0 ; CONTADOR DEL CARACTER
MOV AX,0
CALL CONTAR_CAR
HLT
END