PIO EQU 30H
ORG 1000H
A DB "A"
ORG 2000H
MOV AL,1
OUT PIO+2,AL ; STROBE EN 0, BUSY EN 1 Y LO DEMAS EN 0
MOV AL,0
OUT PIO+3,AL ; INICIALIZO STROBE EN 0
IN AL,PIO
AND AL,0FDH ; STROBE EN 0
OUT PIO,AL
POLL:IN AL,PIO
AND AL,1
JNZ POLL ; POLLING: ESPERO QUE BUSY ESTA EN 0 PARA PODER IMPRIMIR
MOV AL,A
OUT PIO+1,AL
IN AL,PIO
OR AL,2
OUT PIO,AL ; FORZO STROBE A 1 PARA PODER IMPRIMIR
INT 0
END
