CONT EQU 10H
COMP EQU 11H
EOI EQU 20H
INT1 EQU 25H
ORG 20
IPCLK DW 3000H
ORG 1000H
MIN2 DB 30H ; DECENAS DE MINUTOS
MIN1 DB 30H ; UNIDADES DE MINUTOS
DOSP DB 3AH
SEG2 DB 30H ; DECENAS DE SEGUNDOS
SEG1 DB 30H ; UNIDADES DE SEGUNDOS
SALTO DB 13
ORG 3000H
MOV AL,0
OUT CONT,AL

INICIO: INC SEG2
CMP SEG2,36H ; SI LLEGA A 60 SEGUNDOS HAY QUE REINICIAR
JNZ IMPRIMIR ; SINO LLEGA A 60 SEGUNDOS, IMPRIMO
MOV SEG2,30H ; SI SE LLEGO A 60 SEGUNDOS, PONGO 0 DECENAS EN LOS SEGUNDOS E INCREMENTO EN UN MINUTO
INC MIN1 ; INCREMENTO LA UNIDAD DE MINUTOS
CMP MIN1,3AH ; SI SE LLEGO A 9 MINUTOS TENGO QUE PONERLO EN 0
JNZ IMPRIMIR ; SINO LLEGO A 9 MINUTOS, IMPRIMO
MOV MIN1,30H ; PONGO LAS UNIDADES DE MINUTOS EN 0
INC MIN2 ; INCREMENTO EN UNA DECENA LOS MINUTOS
CMP MIN2,36H ; SI HAY 6 DECENAS DE MINUTOS HAY QUE REINICIAR
JNZ IMPRIMIR ; SINO LLEGO A 60 MINUTOS, IMPRIMO
MOV SEG2,30H ; PONGO 0 DECENAS DE SEGUNDOS
MOV MIN1,30H ; PONGO 0 UNIDADES DE MINUTOS
MOV MIN2,30H ; PONGO 0 DECENAS DE MINUTOS (REINICIO TOTAL)
JMP INICIO

IMPRIMIR: MOV BX, OFFSET MIN2
MOV AL,6
INT 7

MOV AL,20H
OUT EOI,AL
IRET
ORG 2000H
CLI
MOV AL,0FDH
OUT EOI+1,AL ; HABILITO LA INTERRUPCION POR TIMER
MOV AL,5
OUT INT1,AL ; ID DE INTERRUPCION
MOV AL,0
OUT CONT,AL ; INICIALIZO EL CONTADOR EN 0
MOV AL,1
OUT COMP,AL ; PONGO AL COMPARADOR EN 10
STI
LAZO: JMP LAZO
INT 0
END
