CONT EQU 10H
COMP EQU 11H
EOI EQU 20H
INT0 EQU 24H
INT1 EQU 25H

ORG 24
IPF10 DW 3000H

ORG 80
IPTIMER DW 3500H

ORG 1000H
MSJ1 DB "INGRESE LA DECENA DE LA CUENTA REGRESIVA: "
FIN1 DB ?
MSJ2 DB "INGRESE LA UNIDAD DE LA CUENTA REGRESIVA: "
FIN2 DB ?
ORG 1200H
DECENA DB ?
UNIDAD DB ?
SALTO DB 13

ORG 3000H
INC DX
MOV AL,EOI
OUT EOI,AL
IRET

ORG 3500H
MOV AL,0
OUT CONT,AL
CMP UNIDAD,30H
JZ DECENAMENOS ; SI LA UNIDAD ES 0, HAY QUE DECREMENTAR LA DECENA
DEC UNIDAD
MOV BX, OFFSET DECENA
MOV AL,3
INT 7
JMP FINALIZAR
DECENAMENOS: CMP DECENA,30H ; SI LA DECENA ES 0, TERMINO LA CUENTA
JZ SALIR
MOV UNIDAD,39H ; SI NO ES 0, MUEVO 9 A LA UNIDAD
DEC DECENA
MOV BX, OFFSET DECENA
MOV AL,3
INT 7
JMP FINALIZAR
SALIR: INC DX
MOV AL,0FFH
OUT EOI+1,AL
FINALIZAR: MOV AL,20H
OUT EOI,AL
IRET

ORG 2000H
CLI
MOV BX, OFFSET MSJ1
MOV AL, OFFSET FIN1 - OFFSET MSJ1
INT 7 ; IMPRIME EL MENSAJE PARA LEER DECENA
MOV BX, OFFSET DECENA
INT 6 ; LEE LA DECENA
MOV BX, OFFSET MSJ2
MOV AL, OFFSET FIN2 - OFFSET MSJ2
INT 7
MOV BX, OFFSET UNIDAD
INT 6
MOV AL,0FEH
OUT EOI+1,AL ; HABILITO LA INTERRUPCION F10
MOV AL,6
OUT INT0,AL ; ID DE F10=6*4=24
MOV AL,20
OUT INT1,AL ; ID DE TIMER=20*4=80
MOV DX,0
STI
LAZO: CMP DX,0
      JZ LAZO
CLI
MOV DX,0
MOV AL,0FCH
OUT EOI+1,AL ; HABILITO LA INTERRUPCION POR TIMER
MOV AL,0
OUT CONT,AL ; PONGO EL CONTADOR EN 0
MOV AL,1
OUT COMP,AL ; PONGO EL COMPARADOR EN 1
STI
LAZO2: CMP DX,0
       JZ LAZO2
INT 0
END